// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20260203095842_RefonteSystèmeRéduction")]
    partial class RefonteSystèmeRéduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCumulative")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxCumulativePercentage")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.0,
                            Description = "IPhone X New",
                            IsCumulative = false,
                            ProductName = "IPhone X",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            Description = "Samsung 10 New",
                            IsCumulative = false,
                            ProductName = "Samsung 10",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
