services:
  ### Service Catalog ###
  
  catalog.database:
    restart: always
    shm_size: 128mb
    ports:
      - "${CATALOG_POSTGRES_PORT}:5432"
    volumes:
      - catalog_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${CATALOG_POSTGRES_PASSWORD}
      POSTGRES_USER: ${CATALOG_POSTGRES_USER}
      POSTGRES_DB: ${CATALOG_POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CATALOG_POSTGRES_USER} -d ${CATALOG_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  catalog.api:
    ports:
      - "6060:${CATALOG_API_PORT}" #http
    environment:
      - ASPNETCORE_HTTP_PORTS=${CATALOG_API_PORT}
      - ConnectionStrings__CatalogConnection=Server=catalog_database;Port=${CATALOG_POSTGRES_PORT};Database=${CATALOG_POSTGRES_DB};Username=${CATALOG_POSTGRES_USER};Password=${CATALOG_POSTGRES_PASSWORD}
  

